### PR TITLE
Update logging

### PR DESCRIPTION
**Pull request by MarcDenman**
As part of #35 I have been trying to make sure and double check that all the middlewares have roughly consistent logging. This PR has the base changes for that, adding MiddlewareName to the base class, expanding the logger interface to allow a couple extra useful methods, extension method to allow a list of errors to be converted into an error string.

Additionally it contains the first few middlewares from the pipeline (except ExceptionHandlerMiddleware)

### CODE REVIEW

**Comment by TomPallister** [comment]
@MarcDenman this is really good, thank you very much!

What do you think about doing something to not have to add {Middleware} everywhere on the logging calls? I don't know if it works in .NET core but in good old fashioned .NET we have CallerMemberName attribute. I don't know if you are familiar with it so forgive me if I'm being patronising. 

We could maybe do this 

```csharp
 CreateLogger([CallerMemberName]string memberName = "")
 {
      //store member name, which should be constructor name, then use it for subsequent logging.
 }
```

What do you think? I'm not sure if this helps but throwing it out there also no idea if it will work!

**Comment by MarcDenman** [comment]
@TomPallister Sorry for the delay in replying, only just seen this.

Nope, not being patronising at all :) I have never come across it, good to learn about hidden gems like that. I will take a look at it and try to see if it helps.

Probably won't get around to it till Saturday, got a busy couple of evenings ahead of me.

**Comment by TomPallister** [comment]
@MarcDenman no worries no rush! Have to fit this stuff in around real life.

**Comment by MarcDenman** [comment]
Started looking at it, [CallerMemberName] will unfortunately not work, as the logger is created within the constructor of the middleware so the value will end up being ".ctor". However, the CreateLogger function has the signature `CreateLogger<T>`, where T is the type you are logging for. I tried to get the type out of the logger, however it doesn't appear to be exposed easily through Microsoft.ILogger.  Instead, I have altered the IOcelotLogger to have a Name property (I want to think of a better name) and altered the constructor for the AspDotNetLogger so the name can be set when it is initialized.

I have also hung a few extension methods(not ideal I know) off IOcelotLogger for a couple common logging statements, i.e. MiddlewareEntered, MiddlewareCompleted

Not sure what to do with the MiddlewareName property, tempted to leave it as it could still be useful  for logging purposes.

Thoughts?

**Comment by TomPallister** [comment]
@MarcDenman looks good. Are you happy to merge this?

**Comment by MarcDenman** [comment]
Yep. happy if you are.

**Pull request merged**
