### PR TITLE
Initial draft for the issue 147 fix

### PR DESCRIPTION
**Pull request by hemantkd**
Hi @TomPallister,

I have hopefully followed the process that you mentioned correctly.
Have a look at the code fixes for the issue #147 

Thanks for your patience!

### CODE REVIEW

**Comment by hemantkd** [comment]
Thanks for letting me @TomPallister! :)

Yes, these questions were also in my chain of thoughts.

If _hostingEnvironment.EnvironmentName is null then string interpolation handles it and just uses an empty string. So, the file name becomes configuration..json and everything still works.

The Unit Tests don't have that scenario at the moment.

**Comment by TomPallister** [comment]
Should it be configuration.json not configuration..json?

I think we should have a test for this!

**Comment by hemantkd** [comment]
configuration..json is still a valid file name but I can understand that it looks odd. I can make the change so that it falls back to configuration.json instead and will write a test for it. Thanks.

**Comment by hemantkd** [comment]
Hi @TomPallister,

Let me know if you're happy with the tests.
I tried to keep them similar to the existing ones and created some private methods to re-use some existing code.
I have also changed the code so that if the environment name is null or empty, the file name used is `configuration.json` instead of `configuration..json`
Do you think we need to worry about trimming the whitespaces from the name?

Let me know your thoughts. Thanks

**Comment by TomPallister** [comment]
@hemantkd looks OK to me...I'm not too worried about trimming whitespace. If you are happy to merge it then I am?

**Comment by hemantkd** [comment]
@TomPallister I'm happy too

**Pull request merged**
