### PR TITLE
Identity Server - Check's issues with Audience and AllowedScopes

### PR DESCRIPTION
**Pull request by juancash**
This PR has been created based on the Issue #100

@JBuenoG detected that when you use authentication options in reroutes and you try to use token with invalid audience, the gateway allows you to access the api.

I created a couple of acceptance test to check two scenarios:

A test which checks a 401 response when we try to access an api with a token requested for another api.
A test which checks a 403 response when we try to access an api with a scope not allowed.

The first scenario has been solved updating the IdentityServer4.AccessTokenValidation nuget package from 1.0.2 to 1.2.0 version. Looking for information about this at the IdentityServer4 repository I found an issue which talks about this problem with oldest versions of IdentityServer4.AccessTokenValidation package.

The second scenario has not been solved yet. I have read about IdentityServer4 and .Net Authentication and Authorization and I read about IdentityServer only does Authentication but not Authorization.

That's mean that we must check the scope on our own or I'm wrong?

### CODE REVIEW

**Comment by juancash** [comment]
@JBuenoG 

I added a bit of code to check the allowed scopes. 

With these changes, if you try to access with a token that contains a scope that is not defined in the allowedScopes property, you get a 403 error (Forbidden). If you want to try the code you can download this branch from my fork until we know if @TomPallister wants to add this feature.

I hope this is useful for you.

**Comment by TomPallister** [comment]
@juancash this looks awesome! Reviewing now.

**Comment by juancash** [comment]
Hi @TomPallister ,
when you go to release the new version of Ocelot in Nuget remember update the version dependency of IdentityServer4 that is necessary to auth works properly.

**Comment by JBuenoG** [comment]
@TomPallister @juancash Great!!

When could be download from NuGet? :)

**Comment by TomPallister** [comment]
@JBuenoG Im working on it ASAP! We have broken the build process in AppVeyor somehow so im trying to work that out!

**Comment by TomPallister** [comment]
@JBuenoG I have pushed a new version (1.4.5) to NuGet.

**Comment by JBuenoG** [comment]
Thx @TomPallister  it works perfect!!
Awesome project!! 🥇

**Comment by TomPallister** [comment]
@JBuenoG thank you! also much thanks to @juancash and @binarymash for helping!! 😄

**Pull request merged**
