### PR TITLE
Test coverage reporting

### PR DESCRIPTION
**Pull request by binarymash**
Don't want to merge this yet, but just want to see if the test coverage appears on the coveralls.io account. I also noticed that there's a new beta of xunit 2.3 just released, which I want to pull in before merging.

### CODE REVIEW

**Comment by TomPallister** [comment]
@binarymash Ive stuck the coveralls badge onto the readme! 😄

**Comment by binarymash** [comment]
Merged, but i still don't see anything at coveralls.io. Not sure what the problem is, but I'll look into it.

In the meantime, you can still see a coverage report when you build locally - see artifacts/UnitTests/index.htm

**Comment by TomPallister** [comment]
@binarymash awesome thanks man! I'll give it a whirl. Im going to look at if I can add you to coveralls.

**Comment by TomPallister** [comment]
@binarymash can you check below and see if that gets you access?

Anyone who has access to the repo on GitHub will be able to see the coverage information on Coveralls. If the other members of your team have been added on GitHub but can't see the repos on Coveralls, have them visit this link: https://coveralls.io/refresh?private=true to refresh their GitHub scope.

source: https://coveralls.zendesk.com/hc/en-us/articles/206384305

I assume because you are admin on the repo you should be able to see it.

**Comment by binarymash** [comment]
Well its a public repo so I guess anyone should be able to see the coverage info. I can see the repo in coveralls but no data.

Might be worth checking that the appveyor environment variable has got the correct repo token. I can't check this in coveralls because I don't have access to the settings for the repo.

**Comment by TomPallister** [comment]
@binarymash rgr

**Comment by TomPallister** [comment]
arghhh i dunno its the same in AppVeyor and coveralls...maybe if we get time tomorrow we can check at lunch!

**Comment by binarymash** [comment]
Working now... think it must have been a problem in coveralls.io.

**Comment by binarymash** [comment]
Merged in 1.5.0-unstable.79.build.199

**Pull request merged**
