### PR TITLE
Feature/upgrade vs 2017

### LINKED ISSUE #32: Upgrade to VS 2017
Vs2017 has released RC4 release [Announcing .NET Core Tools Updates in VS 2017 RC](https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/) ，NET core tooling also RC, we upgrade to the VS2017 project to develop it?

### PR DESCRIPTION
**Pull request by TomPallister**
fixed #32 but we cannot merge this yet as none of the cake addins have been upgraded to use Cake 0.18.0 Ive submitted a pull request for Cake.DoInDirectory and someone else has done Cake.Json.

Hopefully when these are upgraded the cake script will work locally then I can look at AppVeyor.

### CODE REVIEW

**Comment by binarymash** [comment]
What's the problems you're seeing with cake? Do you need cake 0.18.0 right now?

I've been happily running with the VS2017 RC on cake 0.17.0 for weeks. I've not yet upgraded to VS2017RTM, but I've just tested the build all still works in AppVeyor.

The changes I made to switch from VS2015 to VS2017 in my code are at https://github.com/binarymash/responses/pull/10, if that helps. Required some changes to the cake scripts - annoyingly, looks like I did some major refactoring in there at the same time, so it's difficult to see the exact changes I had to make...

**Comment by TomPallister** [comment]
@binarymash I don't know how to specify the cake build version. I upgraded and it all stopped working as expected. 

I'll check your code and see if I can work it out.

Ta!

**Comment by binarymash** [comment]
Actually, my AppVeyor builds reported success but now I look at the log they've actually failed because of Cake.Json.

You can specify the cake version in tools/packages.config - this file is probably ignored at the moment, but just unignore it and check it in with 0.17.0 and you should be in business.

IIRC the changes I had to make to my build scripts when migrating to 2017 were to the dotnetcore commands.

**Comment by TomPallister** [comment]
@binarymash thanks for the help, its working locally on windows for me now but getting this in AppVeyor..

Restore
========================================
Executing task: Restore
error: Invalid input './Ocelot.sln'. The file type was not recognized.
Cake.exe : An error occurred when executing task 'Restore'.

Probably just need to try without the ./ but did you need to make any changes in this area?

**Pull request merged**
