### PR TITLE
#20 - refactored build pipeline

### PR DESCRIPTION
**Pull request by binarymash**
Ok, you definitely won't want to merge this yet - suggest you have a look and decide if this is what you want, branching-wise. 

This code assumes you'll want to git flow, which will give you control over when you publish releases - ie, a release might contain several stories. However, there's a few gotchas I discovered with the gitflow process, which seem to break the versioning, and the integration with github releases adds a bit to the release process which you might not think necessary. So, you might prefer moving to githubflow, which would force you into a new SemVer version for each commit. Shouldn't be difficult to modify this for githubflow, though I haven't tried that.

Anyway, have a look, and then I'll go through it with you in more detail.

### CODE REVIEW

**Comment by binarymash** [comment]
Note that there's stuff in the cake file config that is specific to my fork - feed URLs etc - so these will need changing before any merge. And there'll be stuff to set up in AppVeyor too.

**Comment by TomPallister** [comment]
Thanks @binarymash I'll look into this. Being fair any branching and versioning strategy is going to be better than what I'm doing now!

**Comment by binarymash** [comment]
Hmm, maybe I should have left the existing .bat scripts in there so the current build process doesn't fail :)

I guess the best way to test this all is for you to fork my code and play around with creating releases, configuring AppVeyor etc.

**Comment by TomPallister** [comment]
@binarymash setting aside time tonight to do this review!

**Comment by TomPallister** [comment]
This all looks good @binarymash , I'm happy with the gitflow strategy so going to merge. Only thing is I don't think I can change is the nuget feeds in your pull request so will just merge and fix after. Not like anyone important is using this project yet. The tradeoff is having a broken build for a bit with a good build pipeline going forward I guess.

**Comment by TomPallister** [comment]
@binarymash might move all the build scripts into a /build folder one day as root is getting a little packed!

**Comment by binarymash** [comment]
ok, I can give you a hand getting AppVeyor reconfigured so everything works automagically again. Catch up tomorrow?

**Comment by TomPallister** [comment]
@binarymash thanks sounds good, ill have a poke around see if i can get it building in AppVeyor :)

**Pull request merged**
