### PR TITLE
Fix package publishing

### PR DESCRIPTION
**Pull request by binarymash**
Check that the package is published before merging this!

### CODE REVIEW

**Comment by binarymash** [comment]
So, the CreatePackages step has failed but I'm not sure why because the path looks correct for the releasenote.md. I'm also not sure why this is not failing the whole build.

The build is working fine for me locally when I check out the pull request. @TomPallister can you kick off the build again in Appveyor? I wonder if its just a random failure for some reason.

**Comment by binarymash** [comment]
btw, looks like your feature branches are only publishing their packages for the first commit on the branch. This is because gitversion is currently configured to not generate a unique semver version on this branch (this is the default gitversion behaviour).. It's only the develop branch that generates a unique semver. On my own projects I choose not to publish unstable packages from feature branches..

**Comment by binarymash** [comment]
Good, working now, must have just been a dodgy build in AppVeyor.

**Comment by TomPallister** [comment]
How do you stop it publishing unstable commits? Sorry for noobiness.

**Comment by binarymash** [comment]
I wrote my own code in the cake scripts - have a look at https://github.com/binarymash/responses/blob/develop/build.cake - mostly the same as on this project, but also has a ShouldPublishToUnstableFeed method.

Another reason not to publish all feature branches to the unstable feed is that, depending on name, they might be higher priority than the develop branch. Priority is reverse alphanumeric order, and the develop branch has an "unstable" suffix so if you call your branch "zzz" then this will take higher priority than the most recent develop build, and if you call it "aaa" then it will take lower priority. So, the behaviour is a bit non-deterministic. Pull requests are fine, I think, because they have a "pullrequest" suffix and so will be lower priority than develop.

This is also why I publish my master and release (with a "beta" suffix) branches to the stable feed, and keep unstable develop on it's own feed which people can subscribe to if they want.

**Comment by TomPallister** [comment]
@binarymash stole your publish unstable features code, seemed to work! Thanks.

**Pull request merged**
