### PR TITLE
Cookie proxying and auto redirect configuration #128

### PR DESCRIPTION
**Pull request by aringlot**
HttpHandlerOptions are added to ReRoute configuration and passed down to HttpClientHttpRequester as Request properties.

NB! Properties in FileHttpHandlerOptions are set to true as default not to ruin already existing applications

### CODE REVIEW

**Comment by TomPallister** [comment]
@aringlot Thank you for the contribution! I will review this ASAP!

**Comment by TomPallister** [comment]
The PR is very good thank you! The only problem is that AppVeyor cannot build it for some reason. I will retry the build and then investigate!

**Comment by TomPallister** [comment]
@aringlot I will merge this when the build pipeline is working again.

**Comment by aringlot** [comment]
@TomPallister thank you for your response. I hope, the solution for build issue will be found soon.

**Comment by aringlot** [comment]
@TomPallister 

Hi,

I found out that you found a solution for build issue a couple of hours ago.

To fix this issue in my PR I've merged develop to my local branch.
The good news - acceptance tests passed locally. Here is a screen shot of it: http://prntscr.com/gv5amx.

The bad news - I have no clue why check is green and acceptance tests are red on build machine.

**Comment by TomPallister** [comment]
@aringlot I fixed the build earlier today!

**Comment by TomPallister** [comment]
@aringlot thank you very much for your contribution!

**Comment by aringlot** [comment]
@TomPallister you are welcome! 

Just curious. When do you plan next release ? :)

**Comment by TomPallister** [comment]
@aringlot I have just pushed the release but there is yet another problem with the cake script for releasing to nuget so I need to look into this next ;(

**Comment by TomPallister** [comment]
@aringlot Ive manually pushed a package with your changes

Install-Package Ocelot -Version 1.4.11	

Should work...

**Comment by aringlot** [comment]
@TomPallister thank you !

Unfortunately, I have not enough knowledge to help you with the cake script(

Btw, the only thing I have forgotten is to ask you if I should prepare an example for configuration documentation.

**Comment by TomPallister** [comment]
@aringlot yes please prepare documentation and I can add it to the wiki.

**Comment by aringlot** [comment]
Use HttpHandlerOptions in ReRoute configuration to set up HttpHandler behavior:
- _AllowAutoRedirect_ is a value that indicates whether the request should follow redirection responses.
Set it true if the request should automatically follow redirection responses from the Downstream resource; otherwise false. The default value is true.
- _UseCookieContainer_ is a value that indicates whether the handler uses the CookieContainer property to store server cookies and uses these cookies when sending requests.
The default value is true.

Here is an example configuration:

> {
>   "DownstreamPathTemplate": "/posts",
>   "DownstreamScheme": "https",
>   "DownstreamHost": "jsonplaceholder.typicode.com",
>   "DownstreamPort": 443,
>   "UpstreamPathTemplate": "/posts",
>   "UpstreamHttpMethod": [ "Get" ],
>   "QoSOptions": {
> 	"ExceptionsAllowedBeforeBreaking": 3,
> 	"DurationOfBreak": 10,
> 	"TimeoutValue": 5000
>   },
>   "HttpHandlerOptions": {
> 	"AllowAutoRedirect" : false,
> 	"UseCookieContainer": false
>   }
> }

**Comment by TomPallister** [comment]
@aringlot added to wiki..thanks!

**Pull request merged**
